#ifndef ERRORREPLIES_HPP
#define ERRORREPLIES_HPP

#define ERR_NOSUCHCHANNEL "403"
#define ERR_NOTONCHANNEL "442"
#define ERR_NEEDMOREPARAMS "461"
#define ERR_CHANNELISFULL "471"
#define ERR_INVITEONLYCHAN "473"
#define ERR_BADCHANNELKEY "475"
#define ERR_BADCHANMASK "476"

#endif